### ISSUE TITLE
Attack interface does not support multiple attacking methods.

### ISSUE THREAD

**Issue by DiceSpinner** [DiceSpinner/Lobster-Remake#4]
Fix: Remove attack() from the interface and replace it with other attack methods in the sub-interfaces of Attackable.

**Comment by khushaal-nandwani** [comment]
On it. By sub-interfaces you mean sub-classes of Attackable?

**Comment by DiceSpinner** [comment]
Yeah, that's right. There're two ways I can think of to implement this. The
first way would be declaring extra abstract classes that extend Attackable
which provides additional attacking methods and implement them inside
particle.py. The second way is to directly implement Attackable inside
particle.py but in different ways (polymorphism). This goes the same for
all of the other similar interfaces like "SpellCastable" I declared in
utillities.py for extra creature movements. For now, I can't decide between
them as I'm still experimenting with them. Also, check out the new stuff I
added to the Test_1 branch, it's pretty buggy though, mainly because of the
issue I just added (the diamond inheritance problem), which in some parts
of the inheritance chain are being initialized multiple times which results
in unwanted behaviour (Currently Staminized interface are being initialized
twice when creating the player particle, this results in loss of the
basic_attack action I added inside the Attackable interface ).

khushaal-nandwani ***@***.***> 于2021年7月16日周五 下午10:51写道：

**Comment by khushaal-nandwani** [comment]
I am not sure what type of attacking methods do we need... could you pinpoint the line and file where I can find it

**Comment by DiceSpinner** [comment]
All of the implementation of the interfaces that requires access to particle attributes are done in particles.py. The type of attacking methods is up to your creativity, I have implemented the simplest version which is a melee ranged aoe attack inside SweepAttackable in particles.py. You can try to come up with something else like shooting a laser (utilize the directional interface and use line segments for collision detection).

**Comment by khushaal-nandwani** [comment]
Alright! Sounds cool

**Comment by DiceSpinner** [comment]
Oh btw for line segment collision detection with particles, you might wanna add this method to the Collidable interface. You do collision detection by using the particle you wanna detect on to call this method on the line segments. You can use a tuple of two coordinates to indicate a line segment.

**Comment by DiceSpinner** [comment]
Attackable interface replaced with OffensiveStats interface that only provides offensive fields. Attacks/Spells and other movements can now be added in subclasses of Staminzed/Manaized inside particle_actions.py. Creatures can inherit them to gain access to different movements methods.
